services:
  poli:
    build: .
    ports:
      - "6688:6688"
      - "9091:9091"
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - OTEL_EXPORTER_PROMETHEUS_PORT=9091
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - jaeger
      - prometheus
      - grafana
      - loki
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    volumes:
      - jaeger-storage:/var/lib/jaeger

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /home/challenge/Desktop/poli/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
      - otel-collector

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /home/challenge/Desktop/poli/local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    environment:
      - NODE_ID=poli-node
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /home/challenge/Desktop/poli/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # For OTLP gRPC
      - "55681:55681" # For OTLP HTTP (if needed)

volumes:
  grafana-storage:
  prometheus-data:
  loki-data:
  jaeger-storage:
